In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
np.random.seed(42)
samples = 1000

In [17]:
np.random.seed(42)
X = np.random.rand(samples, 2)
epsilon = np.random.normal(0,1, size=(samples, 1))
y=3*X[0]+5*X[1]+3+epsilon



In [18]:
y

array([[ 6.90560748,  7.96745275],
       [ 6.95670971,  8.01855499],
       [ 7.55711117,  8.61895645],
       ...,
       [ 9.87203284, 10.93387811],
       [ 6.19760675,  7.25945203],
       [ 5.90366568,  6.96551096]])

In [19]:
X = np.c_[np.ones(samples), X]
X

array([[1.        , 0.37454012, 0.95071431],
       [1.        , 0.73199394, 0.59865848],
       [1.        , 0.15601864, 0.15599452],
       ...,
       [1.        , 0.75137509, 0.65695516],
       [1.        , 0.95661462, 0.06895802],
       [1.        , 0.05705472, 0.28218707]])

In [20]:
y

array([[ 6.90560748,  7.96745275],
       [ 6.95670971,  8.01855499],
       [ 7.55711117,  8.61895645],
       ...,
       [ 9.87203284, 10.93387811],
       [ 6.19760675,  7.25945203],
       [ 5.90366568,  6.96551096]])

### 1 gradient descent

In [21]:
def gradient_descent(X,y, learning_rate, epochs):
    m = len(X)
    theta = np.random.randn(X.shape[1], 2)
    print(theta.shape)
    
    for _ in range(epochs):
        gradient = 2 / m * X.T @ (X @ theta - y)
        theta -= learning_rate*gradient
    return theta
theta = gradient_descent(X=X, y=y, epochs=500, learning_rate=0.1)
theta.reshape(-1)

(3, 2)


array([ 7.89497391,  8.94823187, -0.03841141, -0.0315834 , -0.15712472,
       -0.147739  ])

In [22]:
steps = range(1,500, 5)
thetas = np.array([gradient_descent(X, y, epochs=e, learning_rate=0.1, ).reshape(-1) for e in steps])
thetas.shape

(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)


(100, 6)

In [23]:
steps = range(1, 5000, 20)
thetas = np.array([gradient_descent(X, y, epochs=e, learning_rate=0.1, ).reshape(-1) for e in steps])
thetas.shape

(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)
(3, 2)

(250, 6)

### Stochastic gradient descent

In [24]:

t0, t1 = 5,50
def learning_rate_schedule(t):
    return t0/(t+t1)

def sgd(epochs):
    theta = np.random.randn(2,1)
    
    m= len(X)
    
    for epoch in range(epochs):
        for i in range(m):
             random_index = np.random.randint(m)
             x_i = X[random_index : random_index +1]
             y_i = y[random_index : random_index +1]
             
             gradient = 2 * x_i.T.dot(x_i.dot(theta) - y_i)
             eta = learning_rate_schedule(epoch*m+1)
             theta -= eta*gradient
    print(theta)
sgd(10)

ValueError: shapes (1,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)